name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]  # other options: macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: aws-sdk-go-v2

      - name: Checkout smithy-go
        uses: actions/checkout@v2
        with:
          repository: aws/smithy-go
          path: smithy-go
          ref: ep20

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version
          version: latest
          # the following causes golangci-init to do nothing, so all it does is
          # install golang and golangci
          args: --version
          # Show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

      - name: run ci linter
        run: cd aws-sdk-go-v2 && make gen-mod-replace-smithy-. ci-lint
